"""create user_car_gallery_likes table

Revision ID: 379c5732d1ee
Revises: e57bc9d9da88
Create Date: 2025-11-09 15:14:34.541680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379c5732d1ee'
down_revision: Union[str, Sequence[str], None] = 'e57bc9d9da88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
