"""add avatar_url column to users table

Revision ID: 3b3a1bf35999
Revises: 7bc36a519126
Create Date: 2025-09-22 19:50:43.527111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3a1bf35999'
down_revision: Union[str, Sequence[str], None] = '7bc36a519126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('advisor_id', sa.Integer(), nullable=True))
    op.add_column('consultations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('consultations', sa.Column('answered_at', sa.DateTime(), nullable=True))
    op.alter_column('consultations', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'consultations', 'users', ['advisor_id'], ['id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.alter_column('consultations', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('consultations', 'answered_at')
    op.drop_column('consultations', 'status')
    op.drop_column('consultations', 'advisor_id')
    # ### end Alembic commands ###
