"""add accessory images table

Revision ID: 67654b2a2be8
Revises: 38ada5917ef2
Create Date: 2025-11-21 23:56:25.764973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67654b2a2be8'
down_revision: Union[str, Sequence[str], None] = '38ada5917ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_consultation_id', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'consultations', ['consultation_id'], ['id'])
    op.drop_index('ix_users_reset_token', table_name='users')
    op.drop_constraint('users_reset_token_key', 'users', type_='unique')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_reset_token_key', 'users', ['reset_token'])
    op.create_index('ix_users_reset_token', 'users', ['reset_token'], unique=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_consultation_id', 'messages', 'consultations', ['consultation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
