"""add image_url and category columns to accessories

Revision ID: 70e4a65b8c33
Revises: c3c22bd143e2
Create Date: 2025-09-21 19:01:51.708280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e4a65b8c33'
down_revision: Union[str, Sequence[str], None] = 'c3c22bd143e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('accessories', sa.Column('category', sa.String(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('car_name', sa.String(), nullable=False))
    op.add_column('user_car_gallery', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('is_vehicle', sa.Boolean(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('user_car_gallery', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('user_car_gallery', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('fuel_type', sa.String(length=50), nullable=True))
    op.add_column('user_car_gallery', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('engine_spec', sa.String(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('horsepower', sa.Integer(), nullable=True))
    op.add_column('user_car_gallery', sa.Column('top_speed_kmh', sa.Integer(), nullable=True))
    op.drop_column('user_car_gallery', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_gallery', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_car_gallery', 'top_speed_kmh')
    op.drop_column('user_car_gallery', 'horsepower')
    op.drop_column('user_car_gallery', 'engine_spec')
    op.drop_column('user_car_gallery', 'mileage')
    op.drop_column('user_car_gallery', 'fuel_type')
    op.drop_column('user_car_gallery', 'year')
    op.drop_column('user_car_gallery', 'model')
    op.drop_column('user_car_gallery', 'brand')
    op.drop_column('user_car_gallery', 'is_vehicle')
    op.drop_column('user_car_gallery', 'deleted_at')
    op.drop_column('user_car_gallery', 'updated_at')
    op.drop_column('user_car_gallery', 'car_name')
    op.drop_column('accessories', 'category')
    op.drop_column('accessories', 'image_url')
    # ### end Alembic commands ###
