"""add advisor_id and status columns to consultations table

Revision ID: 9869b0da9923
Revises: 3b3a1bf35999
Create Date: 2025-09-22 20:07:21.834708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9869b0da9923'
down_revision: Union[str, Sequence[str], None] = '3b3a1bf35999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
