"""create accessory images table

Revision ID: d65ca38e347d
Revises: 67654b2a2be8
Create Date: 2025-11-21 23:58:51.617091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65ca38e347d'
down_revision: Union[str, Sequence[str], None] = '67654b2a2be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessory_images_id'), 'accessory_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessory_images_id'), table_name='accessory_images')
    op.drop_table('accessory_images')
    # ### end Alembic commands ###
