"""create user_car_gallery_comments table

Revision ID: e57bc9d9da88
Revises: 8ac33b4791c3
Create Date: 2025-11-09 15:11:17.977677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57bc9d9da88'
down_revision: Union[str, Sequence[str], None] = '8ac33b4791c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_car_gallery_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['user_car_gallery.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['user_car_gallery_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_car_gallery_comments_id'), 'user_car_gallery_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_car_gallery_comments_id'), table_name='user_car_gallery_comments')
    op.drop_table('user_car_gallery_comments')
    # ### end Alembic commands ###
